Only assert position changed in OpticalCollector test with double precision:
/home/alund/celeritas_project/celeritas/src/celeritas/alongstep/detail/PropagationApplier.hh:128: error: Propagation of step length 3.945664e-07f due to post-step action 2 leading to distance 3.945664e-07f failed to change position
/home/alund/celeritas_project/celeritas/src/celeritas/phys/detail/TrackingCutExecutor.hh:69: error: Killing track {"geo":{"dir":[-0.311763733625412,0.8268820643424988,-0.4680486023426056],"is_on_boundary":false,"is_outside":false,"pos":[[11.132973670959473,46.96626281738281,-14.058794975280762],"cm"],"volume_id":"sphere"},"mat":"lAr","particle":{"energy":[0.0002947896718978882,"MeV"],"particle_id":"e-"},"sim":{"event_id":0,"num_steps":0,"parent_id":48,"post_step_action":"tracking-cut","status":"errored","step_length":[3.945664275306626e-07,"cm"],"time":[1.9288048935806046e-09,"s"],"track_id":51},"thread_id":2,"track_slot_id":2}: lost 0.00029479 MeV