Suppress another bad warning
This makes *no* sense since because `_M_ptr` is initialized by the
`shared_ptr` constructor before the body of the constructor here.
```
In member function ‘std::__shared_ptr<_Tp, _Lp>::operator bool() const [with _Tp = const celeritas::PhysicsParams; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’,
    inlined from ‘const celeritas::test::GlobalTestBase::SPConstPhysics& celeritas::test::GlobalTestBase::physics()’ at /home/runner/work/celeritas/celeritas/test/celeritas/GlobalTestBase.hh:214:1,
    inlined from ‘celeritas::test::MscTestBase::MscTestBase()’ at /home/runner/work/celeritas/celeritas/test/celeritas/em/MscTestBase.cc:21:64:
/usr/include/c++/14/bits/shared_ptr_base.h:1671:16: error: ‘((const std::__shared_ptr<const celeritas::PhysicsParams, __gnu_cxx::_S_atomic>*)((char*)this + 8))[409].std::__shared_ptr<const celeritas::PhysicsParams, __gnu_cxx::_S_atomic>::_M_ptr’ is used uninitialized [-Werror=uninitialized]
 1671 |       { return _M_ptr != nullptr; }
      |                ^~~~~~
```