Add Windows support (#930)
* Fix corecel errors/warnings on windows

Remove isatty for windows:
```
E:\scale\external\celeritas\src\corecel\io\ColorUtils.cc(13): fatal
error C1083: Cannot open include file: 'unistd.h': No such file or directory
```

String view iterator is not a const char*:
```
E:\scale\external\celeritas\src\corecel\io\StringUtils.cc(66): note:
'std::basic_string_view<char,std::char_traits<char>>::
basic_string_view(const char *const ,const
std::basic_string_view<char,std::char_traits<char>>::size_type)
noexcept': canno
t convert argument 1 from 'std::_String_view_iterator<_Traits>' to
'const char *const '
        with
    [
        _Traits=std::char_traits<char>
    ]
```

'environ' is a macro on windows (boo)
```
E:\scale\external\celeritas\src\corecel\sys\Environment.cc(31): error
C2267: '__p__environ': static functions with block scope are illegal
```

psapi must be included *after* windows.h
```
C:\Program Files (x86)\Windows
Kits\10\\include\10.0.22621.0\\um\psapi.h(132): error C2146: syntax error: missing ';' before identifier 'WINAPI'
```

ptrdiff_t is implicitly converted to long
```
E:\scale\external\celeritas\src\corecel\sys\ScopedMem.cc(125): warning
C4244: 'argument': conversion from 'ptrdiff_t' to 'long', possible loss
of dat
a
```

* Fix truncation warning

* Fix missing include

* Instantiate aligned plane explicitly

* Use 'if constexpr' to avoid choking msvc

This might have relied on compiler optimization stopping the template
instantiation early. With 'if constexpr' this should always be correct.

* Define windows macros

* Fix compiler failure from divide by zero

```
E:\scale\external\celeritas\test\corecel\math\NumericLimits.test.cc(40):
error C2124: divide or mod by zero
```

* Fix integer overflow in windows integer literal

```
E:\scale\external\celeritas\src\celeritas/field/DormandPrinceStepper.hh(144):
warning C4146: unary minus operator applied to unsigned type, result st
ill unsigned
```

* Fix conversion warnings

* Disable dominance warning

```
E:\scale\external\celeritas\src\celeritas\geo\detail\BoundaryAction.hh(37):
warning C4250: 'celeritas::detail::BoundaryAction': inherits
'celeritas::C
oncreteAction::celeritas::ConcreteAction::action_id' via dominance
E:\scale\external\celeritas\src\celeritas/global/ActionInterface.hh(151):
note: see declaration of 'celeritas::ConcreteAction::action_id'
E:\scale\external\celeritas\src\celeritas\geo\detail\BoundaryAction.hh(37):
warning C4250: 'celeritas::detail::BoundaryAction': inherits
'celeritas::C
oncreteAction::celeritas::ConcreteAction::label' via dominance
E:\scale\external\celeritas\src\celeritas/global/ActionInterface.hh(154):
note: see declaration of 'celeritas::ConcreteAction::label'
E:\scale\external\celeritas\src\celeritas\geo\detail\BoundaryAction.hh(37):
warning C4250: 'celeritas::detail::BoundaryAction': inherits
'celeritas::C
oncreteAction::celeritas::ConcreteAction::description' via dominance
```

* Fix implicit cast in step conversion

* Fix MSVC implicit capture weirdness

There are weird scoping rules about static const for lambdas.
```
E:\scale\external\celeritas\test\celeritas\track\TrackInit.test.cc(417):
error C3493: 'num_tracks' cannot be implicitly captured because no
default ca
pture mode has been specified
```

* Fix use of SIGUSR2

```
E:\scale\external\celeritas\app\celer-sim\Transporter.cc(70): error
C2065: 'SIGUSR2': undeclared identifier
```

* Fix narrowing conversion

```
E:\scale\external\celeritas\test\celeritas\em\UrbanMsc.test.cc(281):
error C2397: conversion from 'const int' to 'T' requires a narrowing
conversion
with [T=celeritas::real_type ]
```

More conversion warnings

* Fix missing symbol

* Work around windows environ definition

* Explicitly specify enum type

```
E:\scale\external\celeritas\test\corecel\cont\Range.test.cc(215): error:
Value of: (std::is_same<std::underlying_type<pokemon::Pokemon>::type,
unsigne
d int>::value)
  Actual: false
  Expected: true
```

* Fix windows issues with paths

* Improve dependency logic for building inside another project

* Clang-format

* Work around dumb GCC attribute warning

* Document

* Add default type to quantity based on underlying unit

* Mark quantity functions as noexcept

* Use size_t instead of ptrdiff_t and long int for scoped mem