Release v0.3.0 (#818)
* Fix doxygen errors

* Fix Geant4 version check for ios change

See https://gitlab.cern.ch/geant4/geant4-dev/-/issues/172

* Add documentation

* Add release notes

* Allow local tagging of rc

* Add 'rc' tagging to the release process and reformat as a numbered list

* Ignore calls to cuda stack/heap if device is disabled

This makes the logic easier in the Runner when running regression
problems, where we now have to manually set the cuda stack size.

* Disable CUDA Werror for full-novg

```
FAILED: src/celeritas/CMakeFiles/celeritas.dir/user/DetectorSteps.cu.o
/usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/c++ -Dceleritas_EXPORTS -I/var/jenkins/workspace/Celeritas_PR-818/src -I/var/jenkins/workspace/Celeritas_PR-818/build/include -isystem=/opt/view/include -isystem=/opt/software/linux-ubuntu22.04-x86_64/gcc-11.3.0/openmpi-4.1.4-lkiysbvowwesg6hrpol5mcyro4vzrk5w/include -Werror all-warnings -O0 -g -G --generate-code=arch=compute_70,code=[compute_70,sm_70] -Xcompiler=-fPIC -std=c++17 -MD -MT src/celeritas/CMakeFiles/celeritas.dir/user/DetectorSteps.cu.o -MF src/celeritas/CMakeFiles/celeritas.dir/user/DetectorSteps.cu.o.d -x cu -c /var/jenkins/workspace/Celeritas_PR-818/src/celeritas/user/DetectorSteps.cu -o src/celeritas/CMakeFiles/celeritas.dir/user/DetectorSteps.cu.o
Warning: Function too large, generated debug information may not be accurate.
Error: warning treated as error
```

* Fix documentation

* Fix typos from code review