Fix CUDA 12.3.52 build
I think there's a compiler bug because AllItemsT definitely can't be
constructed from two values...
```
scale/external/celeritas/src/orange/transform/TransformVisitor.hh(127): error: more than one operator "[]" matches these operands:
            function "celeritas::Collection<T, W, M, I>::operator[](celeritas::Collection<T, W, M, I>::ItemRangeT) const [with T=celeritas::real_type, W=celeritas::Ownership::const_reference, M=celeritas::MemSpace::device, I=celeritas::OpaqueId<celeritas::real_type, celeritas::size_type>]" (declared at line 301 of /home/vmuser/build/rnsd/scale/external/celeritas/src/corecel/data/Collection.hh)
            function "celeritas::Collection<T, W, M, I>::operator[](celeritas::Collection<T, W, M, I>::AllItemsT) const [with T=celeritas::real_type, W=celeritas::Ownership::const_reference, M=celeritas::MemSpace::device, I=celeritas::OpaqueId<celeritas::real_type, celeritas::size_type>]" (declared at line 305 of /home/vmuser/build/rnsd/scale/external/celeritas/src/corecel/data/Collection.hh)
            operand types are: const celeritas::TransformVisitor::Reals [ {...} ]
      return T{reals_[{data_offset, data_offset + size}]};
                     ^
```