Don't include ArrayUtils in Types
If ROOT touches it, it dies (missing sincospi)

```
/Users/seth/Code/celeritas-temp/src/corecel/math/Algorithms.hh:533:1: error: no member named '__sincospif' in the global namespace
CELER_WRAP_MATH_FLOAT_DBL_PTR_2(__, sincospi)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/seth/Code/celeritas-temp/src/corecel/math/Algorithms.hh:395:18: note: expanded from macro 'CELER_WRAP_MATH_FLOAT_DBL_PTR_2'
        return ::PREFIX##FUNC##f(value, a, b);                               \
               ~~^
<scratch space>:206:1: note: expanded from here
__sincospif
^
In file included from input_line_9:3:
In file included from /Users/seth/Code/celeritas-temp/src/celeritas/io/ImportData.hh:25:
In file included from /Users/seth/Code/celeritas-temp/src/corecel/math/ArrayUtils.hh:17:
/Users/seth/Code/celeritas-temp/src/corecel/math/Algorithms.hh:533:1: error: no member named '__sincospi' in the global namespace
CELER_WRAP_MATH_FLOAT_DBL_PTR_2(__, sincospi)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/seth/Code/celeritas-temp/src/corecel/math/Algorithms.hh:399:18: note: expanded from macro 'CELER_WRAP_MATH_FLOAT_DBL_PTR_2'
        return ::PREFIX##FUNC(value, a, b);                                  \
               ~~^
<scratch space>:207:1: note: expanded from here
__sincospi
^
Error: /opt/spack/var/spack/environments/celeritas/.spack-env/view/bin/rootcling: compilation failure (/Users/seth/Code/celeritas-temp/build-clhep/lib/libceleritas0cc6355a49_dictUmbrella.h)
```