Try disabling openmp to get rid of weird atomic warnings
```
/opt/rh/devtoolset-7/root/usr/bin/c++  -I/var/jenkins/workspace/Celeritas_PR-569/src -I/var/jenkins/workspace/Celeritas_PR-569/build/include -isystem /opt/rocm/include -isystem /opt/view/include -Wall -Wextra -pedantic -Werror -Wno-error=deprecated-declarations -O3 -DNDEBUG -fopenmp -std=gnu++1z -MD -MT src/celeritas/CMakeFiles/celeritas.dir/track/generated/ProcessSecondaries.cc.o -MF src/celeritas/CMakeFiles/celeritas.dir/track/generated/ProcessSecondaries.cc.o.d -o src/celeritas/CMakeFiles/celeritas.dir/track/generated/ProcessSecondaries.cc.o -c /var/jenkins/workspace/Celeritas_PR-569/src/celeritas/track/generated/ProcessSecondaries.cc
In file included from /var/jenkins/workspace/Celeritas_PR-569/src/celeritas/track/detail/ProcessSecondariesLauncher.hh:10:0,
                 from /var/jenkins/workspace/Celeritas_PR-569/src/celeritas/track/generated/ProcessSecondaries.cc:9:
/var/jenkins/workspace/Celeritas_PR-569/src/corecel/math/Atomics.hh: In instantiation of T celeritas::atomic_add(T*, T) [with T = unsigned int]:
/var/jenkins/workspace/Celeritas_PR-569/src/celeritas/track/detail/ProcessSecondariesLauncher.hh:98:53:   required from ���void celeritas::detail::ProcessSecondariesLauncher<M>::operator()(celeritas::ThreadId) const [with celeritas::MemSpace M = (celeritas::MemSpace)0; celeritas::ThreadId = celeritas::OpaqueId<celeritas::Thread>]
/var/jenkins/workspace/Celeritas_PR-569/src/celeritas/track/generated/ProcessSecondaries.cc:26:9:   required from here
/var/jenkins/workspace/Celeritas_PR-569/src/corecel/math/Atomics.hh:37:5: error: value computed is not used [-Werror=unused-value]
     }
     ^
```