Explicitly declare Thread to avoid Geant4 conflict (#276)
* Attempt workaround for PTL::Thread declaration

```
from acceleritas/app/g4hpc/src/UserTaskManager.cc:10:
acceleritas/external/celeritas/src/base/OpaqueId.hh:121:34: error: using typedef-name ‘PTL::Thread’ after ‘struct’
 using ThreadId = OpaqueId<struct Thread>;
                                  ^~~~~~
In file included from geant4.11.beta/source/externals/ptl/include/PTL/AutoLock.hh:246,
                 from geant4.11.beta/source/externals/ptl/include/PTL/VTask.hh:32,
                 from geant4.11.beta/source/externals/ptl/include/PTL/Task.hh:34,
                 from geant4.11.beta/source/externals/ptl/include/PTL/TaskGroup.hh:35,
                 from acceleritas/app/g4hpc/include/UserTaskManager.hh:10,
                 from acceleritas/app/g4hpc/src/UserTaskManager.cc:8:
geant4.11.beta/source/externals/ptl/include/PTL/Threading.hh:128:41: note: ‘PTL::Thread’ has a previous declaration here
 typedef std::thread                     Thread;
                                         ^~~~~~
In file included from acceleritas/external/celeritas/src/physics/base/Applicability.hh:14,
                 from acceleritas/external/celeritas/src/physics/base/Model.hh:14,
                 from acceleritas/external/celeritas/src/physics/base/PhysicsParams.hh:15,
                 from acceleritas/app/g4hpc/src/UserTaskManager.cc:10:
acceleritas/external/celeritas/src/base/OpaqueId.hh:121:40: error: template argument 1 is invalid
 using ThreadId = OpaqueId<struct Thread>;
```

* Prohibit signed opaque ids