Fix unused attribute error
```
/home/vmuser/build/rnsd/scale/external/celeritas/src/corecel/sys/Stream.cc: In instantiation of 'celeritas::AsyncMemoryResource<Pointer>::pointer celeritas::AsyncMemoryResource<Pointer>::do_allocate(std::size_t, std::size_t) [with Pointer = void*; celeritas::AsyncMemoryResource<Pointer>::pointer = void*; std::size_t = long unsigned int]':
/home/vmuser/build/rnsd/scale/external/celeritas/src/corecel/sys/Stream.cc:137:16:   required from here
/home/vmuser/build/rnsd/scale/external/celeritas/src/corecel/sys/Stream.cc:25:6: error: 'maybe_unused' attribute directive ignored [-Werror=attributes]
 auto AsyncMemoryResource<Pointer>::do_allocate(
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vmuser/build/rnsd/scale/external/celeritas/src/corecel/sys/Stream.cc: In instantiation of 'void celeritas::AsyncMemoryResource<Pointer>::do_deallocate(celeritas::AsyncMemoryResource<Pointer>::pointer, std::size_t, std::size_t) [with Pointer = void*; celeritas::AsyncMemoryResource<Pointer>::pointer = void*; std::size_t = long unsigned int]':
/home/vmuser/build/rnsd/scale/external/celeritas/src/corecel/sys/Stream.cc:137:16:   required from here
/home/vmuser/build/rnsd/scale/external/celeritas/src/corecel/sys/Stream.cc:38:6: error: 'maybe_unused' attribute directive ignored [-Werror=attributes]
 void AsyncMemoryResource<Pointer>::do_deallocate(
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[CTest: warning matched] cc1plus: all warnings being treated as errors
```