Add GitHub actions to CI (#1020)
* Don't default CMake presets to "debug"

* Rename CI presets

* Use CMake BUILD_TESTING to decide to add testing tree

This allows more granularity for building unit tests or just testing the apps

* First iteration of GHA CI

* Integrate style workflow

* Try again

* Fix things, thanks vscode

* Fix exclusion

* Disable clang-format, try different docker url

* REVERTME: single job

* Run as root

see https://github.com/actions/checkout/issues/956

```
Post job cleanup.
/usr/bin/docker exec  8a93ca44215e080743610d80ccea33c624f5d3fce1aa4038cd018c06b13a75a6 sh -c "cat /etc/*release | grep ^ID"
node:internal/fs/utils:347
    throw err;
    ^

Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_56877b46-0efb-448b-8122-6d4d35217f1e'
    at Object.openSync (node:fs:590:3)
    at Object.writeFileSync (node:fs:2202:35)
    at Object.appendFileSync (node:fs:2264:6)
    at Object.issueFileCommand (/__w/_actions/actions/checkout/v3/dist/index.js:2950:8)
    at Object.saveState (/__w/_actions/actions/checkout/v3/dist/index.js:2867:31)
    at Object.8647 (/__w/_actions/actions/checkout/v3/dist/index.js:2326:10)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v3/dist/index.js:18256:43)
    at Object.2565 (/__w/_actions/actions/checkout/v3/dist/index.js:146:34)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v3/dist/index.js:18256:43)
    at Object.9210 (/__w/_actions/actions/checkout/v3/dist/index.js:1141:36) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/__w/_temp/_runner_file_commands/save_state_56877b46-0efb-448b-8122-6d4d35217f1e'
}
```

* Introspect

* Try a different shell

* Source the fucking profile perhaps since it might ignore entrypoint

* No source I guess

* use github env, run tests

* Try to fix environment

* Try again

* Fix (I think?) openmp variables for celer-sim app

* Disable GPU tests at configure time if CELER_DISABLE_DEVICE

* Automatically skip device tests if CELER_DISABLE_DEVICE

* Update versions

* Use std allocateor rather than pinned when no device is available

* Use MPI max numprocs when setting NP default

github runner only has 2

* Disable more tests when GPU unavailable

* fixup! Use std allocateor rather than pinned when no device is available

* Enable all jobs

* Support root disabling (and initialization) from error handler

* Disable device tests if device is disabled at runtime

* Fix thread count for celer-sim with ROOT

* REVERTME: disable all but one ROCM image

* Downgrade to checkout v3

* Fix rocm json and jenkins build names

* Fix root/shared options

* fixup! Disable device tests if device is disabled at runtime

* Fix json

* Dubious ownership

* Fix CELERITAS_TEST_VERBOSE

* Fix matrix and tag fetch

* Try fetch depth

* Try single fetch depth, and fix use of accel example

* Try more fetch depth

* Add ld flags

* Disable example builds that don't currently work

* Fix syntax errors

* Add vecgeom-reldb and fix asan diabling

* Disable reldeb example too

* Remove to-dos

* Exclude changes to rst/md in check

* REVERTME: don't disable device

* Revert "REVERTME: don't disable device"

This reverts commit fbdea2d4d6572875e2c0f71af9cb3e1c6d5b8f71.

* Update 'special' annotations

* Add conflict between hip+assertions and update CI matrix

* Remove profile source and update working dirs

* Update documentation

* Fix image selection and parallelism

* fixup! Fix image selection and parallelism

* Reverse ordering so fine-grained is first