Add clang 18 and gcc 14 builds to CI (#1389)
* Add clang 18 and gcc 14 builds

* Install libpng

* Disable broken GCC warning

* Suppress bad array bound warnings

It seems that GCC deduces that the vector size can be no greater than 2,
but it fails to notice that the conditional won't be visited...
resulting in an out-of-bound error.

```
In file included from /usr/include/c++/14/bits/stl_uninitialized.h:63,
                 from /usr/include/c++/14/memory:69,
                 from /home/runner/work/celeritas/celeritas/src/geocel/rasterize/Image.hh:10,
                 from /home/runner/work/celeritas/celeritas/test/geocel/rasterize/Image.test.cc:8:
In static member function ‘static _Up* std::__copy_move<_IsMove, true, std::random_access_iterator_tag>::__copy_m(_Tp*, _Tp*, _Up*) [with _Tp = celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>; _Up = celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>; bool _IsMove = true]’,
    inlined from ‘_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = true; _II = celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>*; _OI = celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>*]’ at /usr/include/c++/14/bits/stl_algobase.h:521:30,
    inlined from ‘_OI std::__copy_move_a1(_II, _II, _OI) [with bool _IsMove = true; _II = celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>*; _OI = celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>*]’ at /usr/include/c++/14/bits/stl_algobase.h:548:42,
    inlined from ‘_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = true; _II = __gnu_cxx::__normal_iterator<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>*, vector<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>, allocator<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int> > > >; _OI = __gnu_cxx::__normal_iterator<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>*, vector<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>, allocator<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int> > > >]’ at /usr/include/c++/14/bits/stl_algobase.h:555:31,
    inlined from ‘_OI std::move(_II, _II, _OI) [with _II = __gnu_cxx::__normal_iterator<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>*, vector<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>, allocator<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int> > > >; _OI = __gnu_cxx::__normal_iterator<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>*, vector<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>, allocator<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int> > > >]’ at /usr/include/c++/14/bits/stl_algobase.h:683:38,
    inlined from ‘std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::_M_erase(iterator, iterator) [with _Tp = celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>; _Alloc = std::allocator<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int> >]’ at /usr/include/c++/14/bits/vector.tcc:201:6,
    inlined from ‘std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(const_iterator, const_iterator) [with _Tp = celeritas::testdetail::FailedValue<long unsigned int, long unsigned int>; _Alloc = std::allocator<celeritas::testdetail::FailedValue<long unsigned int, long unsigned int> >]’ at /usr/include/c++/14/bits/stl_vector.h:1568:17,
    inlined from ‘testing::AssertionResult celeritas::testdetail::IsRangeEqImpl(Iter1, Iter1, const char*, Iter2, Iter2, const char*, typename FVIT<Iter1, Iter2>::Vec_t&, BinaryOp) [with Iter1 = const long unsigned int*; Iter2 = const long unsigned int*; BinaryOp = std::equal_to<long unsigned int>]’ at /home/runner/work/celeritas/celeritas/test/testdetail/TestMacrosImpl.hh:279:23,
    inlined from ‘testing::AssertionResult celeritas::testdetail::IsVecEq(const char*, const char*, const ContainerE&, const ContainerA&) [with ContainerE = celeritas::Array<long unsigned int, 2>; ContainerA = celeritas::Array<long unsigned int, 2>]’ at /home/runner/work/celeritas/celeritas/test/testdetail/TestMacrosImpl.hh:465:32:
/usr/include/c++/14/bits/stl_algobase.h:452:30: error: ‘void* __builtin_memmove(void*, const void*, long unsigned int)’ offset 480 is out of the bounds [0, 48] [-Werror=array-bounds=]
  452 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

* Suppress another bad warning

This makes *no* sense since because `_M_ptr` is initialized by the
`shared_ptr` constructor before the body of the constructor here.
```
In member function ‘std::__shared_ptr<_Tp, _Lp>::operator bool() const [with _Tp = const celeritas::PhysicsParams; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’,
    inlined from ‘const celeritas::test::GlobalTestBase::SPConstPhysics& celeritas::test::GlobalTestBase::physics()’ at /home/runner/work/celeritas/celeritas/test/celeritas/GlobalTestBase.hh:214:1,
    inlined from ‘celeritas::test::MscTestBase::MscTestBase()’ at /home/runner/work/celeritas/celeritas/test/celeritas/em/MscTestBase.cc:21:64:
/usr/include/c++/14/bits/shared_ptr_base.h:1671:16: error: ‘((const std::__shared_ptr<const celeritas::PhysicsParams, __gnu_cxx::_S_atomic>*)((char*)this + 8))[409].std::__shared_ptr<const celeritas::PhysicsParams, __gnu_cxx::_S_atomic>::_M_ptr’ is used uninitialized [-Werror=uninitialized]
 1671 |       { return _M_ptr != nullptr; }
      |                ^~~~~~
```