CI: add no-debug HIP (ROCM 5.4) build (#569)
* WIP: HIP docker image

* Dockerfile for HIP/CentOS builds

* Use podman for local test if needed

* rocthrust isn't included by default in the rocm docker image

* Fix nodiscard warning

* Use podman if needed

* Increment image suffix

* Fix installation of rocthrust

* Remove suffix for future builds

* Fix symmetry

* Also install rocrand

* Try disabling openmp to get rid of weird atomic warnings

```
/opt/rh/devtoolset-7/root/usr/bin/c++  -I/var/jenkins/workspace/Celeritas_PR-569/src -I/var/jenkins/workspace/Celeritas_PR-569/build/include -isystem /opt/rocm/include -isystem /opt/view/include -Wall -Wextra -pedantic -Werror -Wno-error=deprecated-declarations -O3 -DNDEBUG -fopenmp -std=gnu++1z -MD -MT src/celeritas/CMakeFiles/celeritas.dir/track/generated/ProcessSecondaries.cc.o -MF src/celeritas/CMakeFiles/celeritas.dir/track/generated/ProcessSecondaries.cc.o.d -o src/celeritas/CMakeFiles/celeritas.dir/track/generated/ProcessSecondaries.cc.o -c /var/jenkins/workspace/Celeritas_PR-569/src/celeritas/track/generated/ProcessSecondaries.cc
In file included from /var/jenkins/workspace/Celeritas_PR-569/src/celeritas/track/detail/ProcessSecondariesLauncher.hh:10:0,
                 from /var/jenkins/workspace/Celeritas_PR-569/src/celeritas/track/generated/ProcessSecondaries.cc:9:
/var/jenkins/workspace/Celeritas_PR-569/src/corecel/math/Atomics.hh: In instantiation of T celeritas::atomic_add(T*, T) [with T = unsigned int]:
/var/jenkins/workspace/Celeritas_PR-569/src/celeritas/track/detail/ProcessSecondariesLauncher.hh:98:53:   required from void celeritas::detail::ProcessSecondariesLauncher<M>::operator()(celeritas::ThreadId) const [with celeritas::MemSpace M = (celeritas::MemSpace)0; celeritas::ThreadId = celeritas::OpaqueId<celeritas::Thread>]
/var/jenkins/workspace/Celeritas_PR-569/src/celeritas/track/generated/ProcessSecondaries.cc:26:9:   required from here
/var/jenkins/workspace/Celeritas_PR-569/src/corecel/math/Atomics.hh:37:5: error: value computed is not used [-Werror=unused-value]
     }
     ^
```

* Add hip flags to try to fix build/link errors

Exe linker flags are copied from crusher.

HIP flags, see https://github.com/E3SM-Project/E3SM/issues/4984#issuecomment-1275327873

* Split cmake presets by image and fix hip debug flags

* Try copying docker args from kokkos

* Use clang++ instead of gcc on the rocm job

* Don't install gcc next go-around

* Fix jenkins indentation

* Fix clang warnings

```
/var/jenkins/workspace/Celeritas_PR-569/src/corecel/data/detail/Filler.hh:54:17: error: class template 'Filler' was previously declared as a struct template; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]
extern template class Filler<real_type, MemSpace::device>;
                ^
/var/jenkins/workspace/Celeritas_PR-569/src/corecel/data/detail/Filler.hh:21:8: note: previous use is here
struct Filler;
       ^
```

and

```
/var/jenkins/workspace/Celeritas_PR-569/src/corecel/sys/KernelParamCalculator.device.hh:174:18: error: comparison of integers of different signs: 'celeritas::KernelParamCalculator::dim_type' (aka 'unsigned int') and 'int' [-Werror,-Wsign-compare]
                 <= celeritas::device().max_threads_per_block());
                 ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

* Fix another clang warning

```
/var/jenkins/workspace/Celeritas_PR-569/test/celeritas/random/SequenceEngine.hh:198:30: error: implicit conversion from 'celeritas::test::SequenceEngine::result_type' (aka 'unsigned int') to 'float' changes value from 4294967295 to 4294967296 [-Werror,-Wimplicit-const-int-float-conversion]
    const real_type range  = test::SequenceEngine::max() + real_type(1);
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~ ~
```

* Try a debug build too

* Remove debug run

```
FAILED: src/celeritas/CMakeFiles/celeritas.dir/global/alongstep/AlongStepUniformMscAction.cu.o
/opt/rocm/llvm/bin/clang++ -D__HIP_ROCclr__=1 -Dceleritas_EXPORTS -I/var/jenkins/workspace/Celeritas_PR-569/src -I/var/jenkins/workspace/Celeritas_PR-569/build/include -isystem /opt/view/include -munsafe-fp-atomics -Wno-#warnings -Werror -g -ggdb -O --offload-arch=gfx908 -fPIC -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -std=c++17 -MD -MT src/celeritas/CMakeFiles/celeritas.dir/global/alongstep/AlongStepUniformMscAction.cu.o -MF src/celeritas/CMakeFiles/celeritas.dir/global/alongstep/AlongStepUniformMscAction.cu.o.d -o src/celeritas/CMakeFiles/celeritas.dir/global/alongstep/AlongStepUniformMscAction.cu.o -x hip -c /var/jenkins/workspace/Celeritas_PR-569/src/celeritas/global/alongstep/AlongStepUniformMscAction.cu
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
error: unhandled SGPR spill to memory
14 errors generated when compiling for gfx908.
```