Fix narrowing conversion
```
E:\scale\external\celeritas\test\celeritas\em\UrbanMsc.test.cc(281):
error C2397: conversion from 'const int' to 'T' requires a narrowing
conversion
with [T=celeritas::real_type ]
```

More conversion warnings