Fix and work around some issues on HIP/Crusher (#558)
* Update sumit/crusher build scripts

* Fix debug assertions in HIP code

It seems like the hip-clang compiler validates the host/global function
calls even outside the "device" pass (in which __HIP_DEVICE_COMPILE__ is
defined and the behavior of CELER_ASSERT changes).

```
FAILED: test/CMakeFiles/corecel_data_Collection.dir/corecel/data/Collection.test.cu.o
/opt/rocm-5.1.0/llvm/bin/clang++ -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -D__HIP_ROCclr__=1 -I/ccs/home/s3j/.local/src/celeritas/test -I/ccs/home/s3j/.local/src/celeritas/build/test -I/ccs/home/s3j/.local/src/celeritas/src -I/ccs/home/s3j/.local/src/celeritas/build/include -isystem /sw/crusher/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/googletest-1.10.0-75d47iea3s33viymgxd4goyvq5af3lmm/include -munsafe-fp-atomics -Wno-#warnings -g -ggdb -O --offload-arch=gfx90a -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -std=c++14 -MD -MT test/CMakeFiles/corecel_data_Collection.dir/corecel/data/Collection.test.cu.o -MF test/CMakeFiles/corecel_data_Collection.dir/corecel/data/Collection.test.cu.o.d -o test/CMakeFiles/corecel_data_Collection.dir/corecel/data/Collection.test.cu.o -x hip -c /ccs/home/s3j/.local/src/celeritas/test/corecel/data/Collection.test.cu
/ccs/home/s3j/.local/src/celeritas/test/corecel/data/Collection.test.cu:39:5: error: no matching constructor for initialization of '::celeritas::DebugError'
    CELER_ASSERT(matid);
    ^~~~~~~~~~~~~~~~~~~
/ccs/home/s3j/.local/src/celeritas/src/corecel/Assert.hh:190:32: note: expanded from macro 'CELER_ASSERT'
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ccs/home/s3j/.local/src/celeritas/src/corecel/Assert.hh:154:19: note: expanded from macro 'CELER_DEBUG_ASSERT_'
            throw ::celeritas::DebugError({::celeritas::DebugErrorType::WHICH, \
                  ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ccs/home/s3j/.local/src/celeritas/src/corecel/Assert.hh:435:7: note: candidate constructor (the implicit copy constructor) not viable: call to __host__ function from __global__ function
class DebugError : public std::logic_error
      ^
/ccs/home/s3j/.local/src/celeritas/src/corecel/Assert.hh:435:7: note: candidate constructor (the implicit move constructor) not viable: call to __host__ function from __global__ function
/ccs/home/s3j/.local/src/celeritas/src/corecel/Assert.hh:439:14: note: candidate constructor not viable: call to __host__ function from __global__ function
    explicit DebugError(DebugErrorDetails);
             ^
```

* Fix duplicate symbols in release mode

ld.lld: error: duplicate symbol: celeritas::ParticleTrackView::mass() const
>>> defined at ParticleProcessDiagnostic.cu
>>>            app/CMakeFiles/demo-loop.dir/demo-loop/diagnostic/ParticleProcessDiagnostic.cu.o:(celeritas::ParticleTrackView::mass() const)
>>> defined at StepDiagnostic.cu
>>>            app/CMakeFiles/demo-loop.dir/demo-loop/diagnostic/StepDiagnostic.cu.o:(.text+0x100)

* Simplify function decorator macro definitions

* Disable ROOT on crusher for now

```
ROOT: error: <TTree::Branch>:  The pointer specified for ImportData is not of a class or type known to ROOT
/ccs/home/s3j/.local/src/celeritas/app/celer-export-geant.cc:140: critical: Runtime error: celeritas: runtime error: failed to initialize ROOT ImportData
```

* Build static libraries in lib/ (see #526)

* Manually trigger ROOT initialization

Now it complains but passes (because it re-parses the source code)
```
65: [ RUN      ] RootImporterTest.particles
65: info: Opening ROOT file at /ccs/home/s3j/.local/src/celeritas/test/celeritas/data/four-steel-slabs.root
65: ROOT: error: <TCling::LoadPCM>:  ROOT PCM /autofs/nccs-svm1_home1/s3j/.local/src/celeritas/build-ndebug/test/libceleritas_rdict.pcm file does not exist
65: [       OK ] RootImporterTest.particles (1520 ms)
```

* Tweak formatting for root error handler