Choose a variable name that doesn't conflict with AMD's library
```
/__w/celeritas/celeritas/src/celeritas/random/ElementSelector.hh:60:32: error: too few arguments provided to function-like macro invocation
   60 |         return select_impl_(rng);
      |                                ^
/opt/rocm-6.3.1/lib/llvm/bin/../../../include/hip/amd_detail/amd_hip_runtime.h:175:9: note: macro 'select_impl_' defined here
  175 | #define select_impl_(_1, _2, impl_, ...) impl_
```