Fix MSVC implicit capture weirdness
There are weird scoping rules about static const for lambdas.
```
E:\scale\external\celeritas\test\celeritas\track\TrackInit.test.cc(417):
error C3493: 'num_tracks' cannot be implicitly captured because no
default ca
pture mode has been specified
```